# Default values for mlflow-seldon.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

seldon:
  mlflowmodelpath: gs://hellomlops-prototype-mlflow/mlflow_artifacts/2/aab6375358da433180b5b2f78e128c3d/artifacts/model

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

hook:
  enabled: true
  config:
    MLFLOW_TRACKING_URI: http://mlflow-service.mlflow.svc.cluster.local:5000
    MLFLOW_MODEL_NAME: ElasticnetWineModel
    MLFLOW_STAGE: Production
    MLFLOW_DEPLOY_NAME: wine-example
    DEPLOY_NAMESPACE: default
