# Default values for mlflow-seldon.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

seldon:
  mlflowmodelpath: gs://hellomlops-mlflow/mlflow_artifacts/1/6887f98225b9419f9681d68e7cdd9335/artifacts/random-forest-model


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

mlflow:
  enabled: true
hook:
  enabled: true
  config:
    MLFLOW_TRACKING_URI: http://mlflow-service.mlflow.svc.cluster.local:5000
    MLFLOW_MODEL_NAME: Iris
    MLFLOW_STAGE: Production
    MLFLOW_DEPLOY_NAME: mlflow
    DEPLOY_NAMESPACE: default