# Default values for mlflow-seldon.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

seldon:
  mlflowmodelpath: gs://hellomlops-mlflow/mlflow_artifacts/1/6887f98225b9419f9681d68e7cdd9335/artifacts/random-forest-model
hook:
  MLFLOW_TRACKING_URI: http://mlflow-service.mlflow.svc.cluster.local:5000
  MLFLOW_STAGE: Production
  DEPLOY_NAMESPACE: default
  MLFLOW_MODEL_NAME: Iris
  IMAGE: 
  image:
    repository: gcr.io/hellomlops-tests/mlflow-hook
    pullPolicy: IfNotPresent
    tag: "v2"


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

